package org.csiro.rockstore.entity.postgres;

// Generated 12/08/2015 3:14:54 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * RsCollection generated by hbm2java
 */
@Entity
@Table(name = "rs_collection_audit")
@NamedQueries({
	@NamedQuery(
			name="RsCollectionAudit.findCollectionById",
		    query="SELECT c FROM RsCollectionAudit c WHERE c.collectionId = :collectionId"
		)			
})	
public class RsCollectionAudit implements java.io.Serializable {
		
	private int id;
	private String collectionId;
	private String project;
	private String staffIdFieldManager;
	private String staffidResponsible;
	private String projectResult;
	private String projectPublication;
	private Date projectCloseDate;
	private Boolean availableToPublic;
	private Date archiveDue;	
	private int version;
	private String lastUpdateUser;
	private String operation;
	private Date auditTimestamp;
	
	public RsCollectionAudit() {
	}
	
	

	
	@Column(name = "id",insertable=false, updatable=false, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(insertable=false,updatable=false, name = "collection_id", length = 50)
	@Generated(GenerationTime.INSERT)
	public String getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(String collectionId) {
		this.collectionId = collectionId;
	}

	@Column(name = "project", length = 100)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "staffid_field_manager", length = 100)
	public String getStaffIdFieldManager() {
		return this.staffIdFieldManager;
	}

	public void setStaffIdFieldManager(String staffIdFieldManager) {
		this.staffIdFieldManager = staffIdFieldManager;
	}

	@Column(name = "staffid_responsible", length = 100)
	public String getStaffidResponsible() {
		return this.staffidResponsible;
	}

	public void setStaffidResponsible(String staffidResponsible) {
		this.staffidResponsible = staffidResponsible;
	}

	@Column(name = "project_result", length = 200)
	public String getProjectResult() {
		return this.projectResult;
	}

	public void setProjectResult(String projectResult) {
		this.projectResult = projectResult;
	}

	@Column(name = "project_publication", length = 200)
	public String getProjectPublication() {
		return this.projectPublication;
	}

	public void setProjectPublication(String projectPublication) {
		this.projectPublication = projectPublication;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "project_close_date", length = 29)
	public Date getProjectCloseDate() {
		return this.projectCloseDate;
	}

	public void setProjectCloseDate(Date projectCloseDate) {
		this.projectCloseDate = projectCloseDate;
	}

	@Column(name = "available_to_public")
	public Boolean getAvailableToPublic() {
		return this.availableToPublic;
	}

	public void setAvailableToPublic(Boolean availableToPublic) {
		this.availableToPublic = availableToPublic;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "archive_due", length = 29)
	public Date getArchiveDue() {
		return this.archiveDue;
	}

	public void setArchiveDue(Date archiveDue) {
		this.archiveDue = archiveDue;
	}
	
	@Id	
	@Column(name = "version", insertable=false, updatable=false)
	public int getVersion() {
		return this.version;
	}
		
	public int setVersion(int version) {
		return this.version= version;
	}
	
	@Column(name = "last_update_user")	
	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}
	
	public String setLastUpdateUser(String lastUpdateUser) {
		return this.lastUpdateUser = lastUpdateUser;
	}
	
	
	@Column(name = "operation")	
	public String getOperation() {
		return this.operation;
	}
	
	public String setOperation(String operation) {
		return this.operation = operation;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "audit_timestamp", length = 29)	
	public Date getAuditTimestamp() {
		return this.auditTimestamp;
	}
	
	public Date setAuditTimestamp(Date auditTimestamp) {
		return this.auditTimestamp = auditTimestamp;
	}

	


}
