package org.csiro.rockstore.entity.postgres;

// Generated 12/08/2015 3:14:54 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RsSubcollection generated by hbm2java
 */
@Entity
@Table(name = "sample_range_by_subcollection", uniqueConstraints = @UniqueConstraint(columnNames = "subcollection_id"))
public class SampleRangeBySubcollection implements java.io.Serializable {

	
	private String subcollectionId;
	private String minContainer;
	private String maxContainer;
	private String minSample;
	private String maxSample;
	
	public SampleRangeBySubcollection(){}
	

	@Id
	@Column(insertable=false,updatable=false, name = "subcollection_id", unique = true, length = 100)	
	public String getSubcollectionId() {
		return this.subcollectionId;
	}

	public void setSubcollectionId(String subcollectionId) {
		this.subcollectionId = subcollectionId;
	}

	@Column(insertable=false,updatable=false, name = "min_container", length = 100)
	public String getMinContainer() {
		return this.minContainer;
	}

	public void setMinContainer(String minContainer) {
		this.minContainer = minContainer;
	}

	@Column(insertable=false,updatable=false, name = "max_container", length = 100)
	public String getMaxContainer() {
		return this.maxContainer;
	}

	public void setMaxContainer(String maxContainer) {
		this.maxContainer = maxContainer;
	}
	
	@Column(insertable=false,updatable=false, name = "min_sample", length = 100)
	public String getMinSample() {
		return this.minSample;
	}

	public void setMinSample(String minSample) {
		this.minSample = minSample;
	}
	
	@Column(insertable=false,updatable=false, name = "max_sample", length = 100)
	public String getMaxSample() {
		return this.maxSample;
	}

	public void setMaxSample(String maxSample) {
		this.maxSample = maxSample;
	}

}
