package org.csiro.rockstore.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "staffs")
@NamedQueries({	
	@NamedQuery(
			name="Staff.getAuthenticated",
		    query="SELECT c FROM Staff c order by c.contactName"
	),
	@NamedQuery(
			name="Staff.findStaffByName",
		    query="SELECT c FROM Staff c where c.contactName =:contactName order by c.contactName" 
	)	
})	
public class Staff implements java.io.Serializable {

	private int staffId;
	private String organization;
	private String contactName;
	private String phone;
	private String email;
	private String address;
	private String city;
	private String state;
	private String zipCode;
	

	public Staff() {
	}

	public Staff(String organization, String contactName) {
		
		this.organization = organization;
		this.contactName = contactName;
	}

	public Staff(String organization, String contactName, String phone, String email,
			String address, String city, String state, String zipCode) {
		
		this.organization = organization;
		this.contactName = contactName;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		
	}

	@Id
	@Column(name = "staff_id", updatable=false, unique = true, nullable = false)
	@SequenceGenerator(name="staffs_staff_id_seq",sequenceName="staffs_staff_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="staffs_staff_id_seq")
	public int getStaffId() {
		return this.staffId;
	}

	public void setStaffId(int staffId) {
		this.staffId = staffId;
	}

	@Column(name = "organization", nullable = false)
	public String getOrganization() {
		return this.organization;
	}

	public void setOrganization(String organization) {
		this.organization = organization;
	}


	@Column(name = "contact_name",unique = true, nullable = false)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip_code")
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}


}
