package org.csiro.rockstore.entity.postgres;

// Generated 04/08/2015 2:17:37 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "user_permission")
@NamedQueries({	
	@NamedQuery(
			name="UserPermission.getPermissionByStaff",
		    query="SELECT c FROM UserPermission c where c.staff =:staff"
	),
	@NamedQuery(
			name="UserPermission.getPermissionList",
		    query="SELECT c FROM UserPermission c"
	)
	
})	
public class UserPermission implements java.io.Serializable {

	
	private String staff;
	private Boolean admin;
	private Boolean canEdit;	
	private Boolean geologist;


	public UserPermission() {
	}

	public UserPermission(String staff, Boolean admin,Boolean canEdit,Boolean geologist ) {
		
		this.staff = staff;
		this.admin = admin;
		this.canEdit = canEdit;
		this.geologist = geologist;
	}

	

	@Id
	@Column(name = "staff", unique = true, nullable = false)
	public String getStaff() {
		return this.staff;
	}

	public void setStaff(String staff) {
		this.staff = staff;
	}

	

	@Column(name = "admin")
	public Boolean getAdmin() {
		return this.admin;
	}

	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}
	
	@Column(name = "can_edit")
	public Boolean getCanEdit() {
		return this.canEdit;
	}

	public void setCanEdit(Boolean canEdit) {
		this.canEdit = canEdit;
	}
	
	@Column(name = "geologist")
	public Boolean getGeologist() {
		return this.geologist;
	}

	public void setGeologist(Boolean geologist) {
		this.geologist = geologist;
	}



}
